### ISSUE TITLE
The main title doesn't scale down with the window size.

### ISSUE THREAD

**Issue by dylanaraps** [tudurom/albumify#11]
The title at the top of the page doesn't  change size with the window, this makes it huge and misaligned on mobile devices. 

I'm about to go to bed but I can send a PR in the morning if you'd like.

**Comment by tudurom** [comment]
I can fix it with the `@media` thing.

**Comment by dylanaraps** [comment]
That's a media query and it will do the trick. :)

**Comment by tudurom** [comment]
Solved in 433358c4b57d561eb19567c2e47e02bbfe7cdf33. I will leave it open and wait for your opinion.

**Comment by tudurom** [comment]
Tested on my 480p phone.

**Comment by dylanaraps** [comment]
Works fine :+1:
