### ISSUE TITLE
Add the album title to view.html

### ISSUE THREAD

**Issue by dylanaraps** [tudurom/albumify#3]
Right now the album title only appears in the tab as a tab title, it would be awesome if it appeared right at the top of `view.html`. The resulting page would look like this:

``` markdown
# Album Title

# Image title
image here

# Image title
image here

```

The css styling is there already all we have to do is add something like this to the top of the page. I attempted this but couldn't get it to work, I've got no experience with javascript. :)

``` html
<h1>Album Title</h1>
```

**Comment by dylanaraps** [comment]
Thanks

**Comment by tudurom** [comment]
Thank you too.
